<?php


namespace Tests\Infrastructure\Messaging\Adapters;


use Infrastructure\Messaging\Adapters\RabbitMQ;
use PhpAmqpLib\Channel\AMQPChannel;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use Tests\Infrastructure\Base;

class RabbitMQTest extends Base
{
    /** @var RabbitMQ */
    protected $rabbit;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->rabbit = new RabbitMQ('127.0.0.1', '/', 'guest', 'guest');
    }

    public function testPublish() {
        $value = bin2hex(random_bytes(16));
        $this->assertTrue($this->rabbit->publish(json_encode(['test' => $value])));
    }

    public function testGetConnection() {
        $conn = $this->rabbit->getConnection();
        $this->assertInstanceOf(AMQPStreamConnection::class, $conn);
    }

    public function testGetChannel() {
        $this->assertInstanceOf(AMQPChannel::class, $this->rabbit->getChannel());
    }
}