<?php


namespace Tests\Infrastructure\Messaging\Adapters;


use Infrastructure\Messaging\Adapters\RabbitMQ;
use Tests\Infrastructure\Base;

class RabbitMQTest extends Base
{
    /** @var RabbitMQ */
    protected $rabbit;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->rabbit = new RabbitMQ('127.0.0.1', '/', 'guest', 'guest');
    }

    public function testPublish() {
        $value = bin2hex(random_bytes(16));
        $this->assertTrue($this->rabbit->publish(json_encode(['test' => $value])));
    }
}