<?php


namespace Tests\Infrastructure\Messaging\Middleware;


use Doctrine\ORM\EntityManager;
use Infrastructure\Messaging\Middleware\EntityManagerMiddleware;
use Mockery\Mock;
use Tests\Infrastructure\Base;
use Tests\Infrastructure\BaseCommand;

class EntityManagerMiddlewareTest extends Base
{
    protected $em;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $em = \Mockery::mock(EntityManager::class);
        $em->shouldReceive('clear')
            ->once()
            ->andReturn();


        $this->em = $em;
    }

    public function testExecute() {
        $middleware = new EntityManagerMiddleware($this->em);
        $baseCommand = new BaseCommand(bin2hex(random_bytes(8)));

        $executed = false;
        $middleware->execute($baseCommand, function ($thing) use (&$executed) {
            $executed = true;
        });

        $this->assertTrue($executed);
    }
}