<?php


namespace Tests\Infrastructure\Messaging\Middleware;


use Infrastructure\Messaging\Middleware\LockingMiddleware;
use Tests\Infrastructure\Base;
use Tests\Infrastructure\BaseCommand;

class LockingMiddlewareTest extends Base
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExecute() {
        $middleware = new LockingMiddleware();

        $command = new BaseCommand(bin2hex(random_bytes(8)));

        $executed = false;
        $middleware->execute($command, function ($thing) use (&$executed) {
            $executed = true;
        });

        $this->assertTrue($executed);
    }

    public function testExceptionExecute() {
        $middleware = new LockingMiddleware();

        $command = new BaseCommand(bin2hex(random_bytes(8)));

        $executed = false;
        try {
        $middleware->execute($command, function ($thing) use ($command) {
            throw new \Exception($command->getCommandName());
        });
        } catch (\Exception $exception) {
            if ($exception->getMessage() === $command->getCommandName()) {
                $executed = true;
            }
        }

        $this->assertTrue($executed);
    }
}